# Generated by Django 3.1 on 2021-08-16 02:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='分类名')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('citations', models.IntegerField(default=0, null=True, verbose_name='引用次数')),
                ('is_delete', models.IntegerField(choices=[(1, '已删除'), (0, '正常')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='标签名')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('citations', models.IntegerField(default=0, null=True, verbose_name='引用次数')),
                ('is_delete', models.IntegerField(choices=[(1, '已删除'), (0, '正常')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '简介信息', 'verbose_name_plural': '简介信息'},
        ),
        migrations.AddField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avater',
            field=models.ImageField(upload_to=core.models.upload_path, verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='标题')),
                ('content_md', models.TextField(blank=True, null=True, verbose_name='内容markdown格式')),
                ('content_html', models.TextField(blank=True, null=True, verbose_name='内容html格式')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读数')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.IntegerField(choices=[(1, '已删除'), (0, '正常')], default=0, verbose_name='状态')),
                ('category', models.ManyToManyField(to='core.Category')),
                ('tag', models.ManyToManyField(to='core.Tag')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_time'],
            },
        ),
    ]
